config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/yes', as: 'rails_admin'
  get 'home/index'

  resources :medicine_intake_logs
  resources :doctor_notifications
  resources :in_patients
  resources :prescriptions
  resources :medicines
  resources :doctor_appointments
  resources :doctors do
    get 'login', :on => :collection
    post 'signin', :on => :collection
    get 'logout', :on => :collection
  end
  devise_for :users, controllers: {
    registrations: "users/registrations",
    # Add this
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  root :to => 'home#index'
end

app/models/in_patient.rb
class InPatient < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/controllers/in_patients_controller.rb
class InPatientsController < ApplicationController
  before_action :set_in_patient, only: [:show, :edit, :update, :destroy]
  before_action :set_doctors_and_users, only: [:new, :edit]
  before_action :set_doctor_user_from_session, only: [:index, :new]

  # GET /in_patients
  def index
    if @doctor && @user
      @in_patients = InPatient.where(user_id: @user.id, doctor_id: @doctor.id)
    elsif @doctor
      @in_patients = InPatient.where(doctor_id: @doctor.id)
    elsif @user
      @in_patients = InPatient.where(user_id: @user.id)
    else
      @in_patients = InPatient.all
    end
  end

  # GET /in_patients/1
  def show
  end

  # GET /in_patients/new
  def new
    @in_patient = InPatient.new
  end

  # GET /in_patients/1/edit
  def edit
  end

  # POST /in_patients
  def create
    @in_patient = InPatient.new(in_patient_params)

    respond_to do |format|
      if @in_patient.save
        format.html { redirect_to @in_patient, notice: 'In patient was successfully created.' }
        format.json { render :show, status: :created, location: @in_patient }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /in_patients/1
  # PATCH/PUT /in_patients/1.json
  def update
    respond_to do |format|
      if @in_patient.update(in_patient_params)
        format.html { redirect_to @in_patient, notice: 'In patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @in_patient }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /in_patients/1
  # DELETE /in_patients/1.json
  def destroy
    @in_patient.destroy
    respond_to do |format|
      format.html { redirect_to in_patients_url, notice: 'In patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_in_patient
      @in_patient = InPatient.find(params[:id])
    end

    def set_doctors_and_users
      @doctors = Doctor.all
      @users = User.all
    end

    def set_doctor_user_from_session
      #initialise ids
      doctor_id = nil
      user_id = nil

      # find user
      if session[:user_id]
        user_id = session[:user_id]
      elsif request.query_parameters['userId']
        user_id = request.query_parameters['userId']
      end
      if user_id
        @user = User.find(user_id)
      end

      # find doctor
      if session[:doctor_id]
        doctor_id = session[:doctor_id]
      elsif request.query_parameters['doctorId']
        doctor_id = request.query_parameters['doctorId']
      end
      if doctor_id
        @doctor = Doctor.find(doctor_id)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def in_patient_params
      params.require(:in_patient).permit(:user_id, :doctor_id, :visting_since, :notes, :status, :for_practice)
    end
end

app/helpers/in_patients_helper.rb
module InPatientsHelper
end

app/views/in_patients/_form.html.erb
<%= form_with(model: in_patient, class: 'pure-form pure-form-aligned', local: true) do |form| %>
  <% if in_patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(in_patient.errors.count, "error") %> prohibited this in_patient from being saved:</h2>

      <ul>
      <% in_patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @doctor %>
    <div class="field pure-control-group">Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></div>
    <%= form.hidden_field :doctor_id, :value => @doctor.id%>
  <% else %>
    <div class="field pure-control-group">
      <%= form.label :doctor_id %>
      <%= form.select :doctor_id, options_for_select(@doctors.map{ |d| [d.first_name+' '+d.last_name, d.id, {'username'=>d.username}] }, selected_key = form.object.doctor_id) %>
    </div>
  <% end %>

  <% if @user %>
    <div class="field pure-control-group">User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></div>
    <%= form.hidden_field :user_id, :value => @user.id%>
  <% else %>
    <div class="field pure-control-group">
      <%= form.label :user_id %>
      <%= form.select :user_id, options_for_select(@users.map{ |u| [u.first_name+' '+u.last_name, u.id, {'username'=>u.username}] }, selected_key = form.object.user_id) %>
    </div>
  <% end %>
  <div class="field pure-control-group">
    <%= form.label :visting_since %>
    <%= form.datetime_select :visting_since, id: :in_patient_visting_since %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :notes %>
    <%= form.text_area :notes, id: :in_patient_notes %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :status %>
    <%= form.text_field :status, id: :in_patient_status %>
  </div>

  <div class="field pure-control-group">
    <%= form.label :for_practice %>
    <%= form.text_field :for_practice, id: :in_patient_for_practice %>
  </div>

  <div class="actions">
    <%= form.submit 'submit', :class => 'pure-button'%>
  </div>
<% end %>

app/views/in_patients/edit.html.erb
<h1>Editing In Patient</h1>

<%= render 'form', in_patient: @in_patient %>

<%= link_to 'Show', @in_patient, class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', in_patients_path, class: 'pure-button  button-secondary'  %>

app/views/in_patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>In Patients</h1>
<% if @user %>
  <h3>User: <%= @user.first_name %>&nbsp;<%= @user.last_name %></h3>
<% end %>
<% if @doctor %>
  <h3>Doctor: <%= @doctor.first_name %>&nbsp;<%= @doctor.last_name %></h3>
<% end %>

<table class="pure-table pure-table-bordered">
  <thead>
    <tr class="<%= cycle('pure-table-odd', '') -%>">
      <th>User</th>
      <th>Doctor</th>
      <th>Visting since</th>
      <th>Notes</th>
      <th>Status</th>
      <th>For practice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @in_patients.each do |in_patient| %>
      <tr class="<%= cycle('pure-table-odd', '') -%>">
        <td><%= in_patient.user.first_name %>&nbsp;<%= in_patient.user.last_name %></td>
        <td><%= in_patient.doctor.first_name %>&nbsp;<%= in_patient.doctor.last_name %></td>
        <td><%= in_patient.visting_since %></td>
        <td><%= in_patient.notes %></td>
        <td><%= in_patient.status %></td>
        <td><%= in_patient.for_practice %></td>
        <td><%= link_to 'Show', in_patient, class: 'pure-button pure-button-primary'  %></td>
        <td><%= link_to 'Edit', edit_in_patient_path(in_patient), class: 'pure-button button-secondary'  %></td>
        <td><%= link_to 'Destroy', in_patient, method: :delete, data: { confirm: 'Are you sure?' }, class: 'pure-button  button-warning'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New In Patient', new_in_patient_path, class: 'pure-button  button-secondary'  %>

app/views/in_patients/new.html.erb
<h1>New In Patient</h1>

<%= render 'form', in_patient: @in_patient %>

<%= link_to 'Back', in_patients_path %>

app/views/in_patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @in_patient.user.first_name %>&nbsp;<%= @in_patient.user.last_name %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @in_patient.doctor.first_name %>&nbsp;<%= @in_patient.doctor.last_name %>
</p>

<p>
  <strong>Visting since:</strong>
  <%= @in_patient.visting_since %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @in_patient.notes %>
</p>

<p>
  <strong>Status:</strong>
  <%= @in_patient.status %>
</p>

<p>
  <strong>For practice:</strong>
  <%= @in_patient.for_practice %>
</p>

<%= link_to 'Edit', edit_in_patient_path(@in_patient), class: 'pure-button  pure-button-primary'  %> |
<%= link_to 'Back', in_patients_path, class: 'pure-button  button-secondary'  %>